# Generated by Django 6.0.3 on 2026-04-03 06:17

import django.db.models.deletion
import drivers.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_number', models.CharField(max_length=30, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=drivers.models.driver_upload_path)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=drivers.models.driver_upload_path)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('last_logout_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'driver'}, on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverLoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_logs', to='drivers.driver')),
            ],
            options={
                'db_table': 'driver_login_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
