# Generated by Django 4.2.21 on 2026-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
