# Generated by Django 6.0.3 on 2026-04-03 06:17

import django.db.models.deletion
import uuid
import vehicles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('rc_document', models.FileField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('permit_document', models.FileField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('aadhar_card', models.FileField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('license_document', models.FileField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('owner_photo', models.ImageField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('car_photo', models.ImageField(blank=True, null=True, upload_to=vehicles.models.car_upload_path)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'car'}, on_delete=django.db.models.deletion.CASCADE, related_name='car_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars',
                'ordering': ['-created_at'],
            },
        ),
    ]
