# Generated by Django 6.0.3 on 2026-04-03 06:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('drop_date', models.DateField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('type_of_trip', models.CharField(choices=[('local', 'Local'), ('outstation', 'Outstation'), ('airport', 'Airport'), ('rental', 'Rental')], default='local', max_length=20)),
                ('pickup_location', models.CharField(max_length=255)),
                ('drop_location', models.CharField(blank=True, max_length=255)),
                ('fare', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('waiting_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_new_customer', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='customers.customer')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='drivers.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='vehicles.car')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
