# Generated by Django 6.0.3 on 2026-04-03 06:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commission_defaults',
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('car_percentage', models.DecimalField(decimal_places=2, default=60, max_digits=5)),
                ('driver_percentage', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('admin_percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('car_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('driver_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='bookings.booking')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
